# ~/.config/starship.toml
# Config file for starship for iop098321qwe

# Disable newlines
add_newline = false

# Set custom prompt
format = '''
[â”Œâ”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€>](bold #a6e3a1)
[â”‚](bold #a6e3a1)$os$username$hostname$directory$rust$package$git_branch$git_status$cmd_duration
[â””>](bold #a6e3a1)$character '''

# Customize the username module
[username]
disabled = true
show_always = true
style_user = "bold #f9e2af"

# Customize the hostname module
[hostname]
disabled = false
style = "bold #94e2d5"

# Customize the os module
[os]
disabled = true
style = "bold #ffffff"

# Customize the character module
[character]
disabled = false
success_symbol = "[â¯](bold #a6e3a1)"
error_symbol = "[â¯](bold #f38ba8)"
vimcmd_symbol = "[â®](bold #a6e3a1)"
vimcmd_replace_one_symbol = "[â®](bold #b4befe)"
vimcmd_replace_symbol = "[â®](bold #b4befe)"
vimcmd_visual_symbol = "[â®](bold #f9e2af)"

# Customize the directory module
[directory]
disabled = false
truncation_length = 5
truncation_symbol = '.../'
style = "bold #89b4fa"

# Customize the git_branch module
[git_branch]
disabled = false
symbol = "î‚  "          # Optional: Git branch symbol
style = "bold #cba6f7"

# Customize the git_status module
[git_status]
disabled = false
conflicted = "âœ–"                              # Conflicted file
ahead = "â‡¡${count}"                           # Ahead of upstream
behind = "â‡£${count}"                          # Behind upstream
diverged = "â‡•â‡¡${ahead_count}â‡£${behind_count}" # Diverged
untracked = "?"                               # Untracked files
stashed = "!"                                 # Stashed changes
modified = "âœš"                                # Modified files
staged = "â—"                                  # Staged files
renamed = "âœ"                                 # Renamed files
deleted = "â€“"                                 # Deleted files
style = "bold #f38ba8"

# Customize the rust module
[rust]
symbol = "ğŸ¦€ "
style = "bold #f38ba8"
disabled = false

# Customize the package module
[package]
disabled = false

# Customize the command duration module
[cmd_duration]
min_time = 1
style = 'bold #89b4fa'
format = 'took [$duration]($style)'
disabled = false
