# ~/.config/starship.toml
# Config file for starship for iop098321qwe

# Disable newlines
add_newline = false

# Set custom prompt
format = '''
(bold #a6e3a1)$directory$rust$package$git_branch$git_status$cmd_duration
'''

# Customize the username module
[username]
show_always = true
disabled = false
style_user = "bold #f9e2af"

# Customize the hostname module
[hostname]
disabled = false
style = "bold #94e2d5"

# Customize the os module
[os]
disabled = true
style = "bold #ffffff"

# Customize the character module
[character]
disabled = false
success_symbol = "[‚ùØ](bold #a6e3a1)"
error_symbol = "[‚ùØ](bold #f38ba8)"
vimcmd_symbol = "[‚ùÆ](bold #a6e3a1)"
vimcmd_replace_one_symbol = "[‚ùÆ](bold #b4befe)"
vimcmd_replace_symbol = "[‚ùÆ](bold #b4befe)"
vimcmd_visual_symbol = "[‚ùÆ](bold #f9e2af)"

# Customize the directory module
[directory]
truncation_length = 5
truncation_symbol = '.../'
style = "bold #89b4fa"
disabled = false

# Customize the git_branch module
[git_branch]
symbol = "ÓÇ† "          # Optional: Git branch symbol
style = "bold #cba6f7"
disabled = false

# Customize the git_status module
[git_status]
conflicted = "‚úñ"                              # Conflicted file
ahead = "‚á°${count}"                           # Ahead of upstream
behind = "‚á£${count}"                          # Behind upstream
diverged = "‚áï‚á°${ahead_count}‚á£${behind_count}" # Diverged
untracked = "?"                               # Untracked files
stashed = "!"                                 # Stashed changes
modified = "‚úö"                                # Modified files
staged = "‚óè"                                  # Staged files
renamed = "‚ûú"                                 # Renamed files
deleted = "‚Äì"                                 # Deleted files
style = "bold #f38ba8"
disabled = false

# Customize the rust module
[rust]
symbol = "ü¶Ä "
style = "bold #f38ba8"
disabled = false

# Customize the package module
[package]
disabled = false

# Customize the command duration module
[cmd_duration]
min_time = 1
style = 'bold #89b4fa'
format = 'took [$duration]($style)'
disabled = false
